### ISSUE TITLE
Do not run create_release_and_deploy step if the version number has not changed. 

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/ixnetwork#151] opened 2020-12-10 18:14 UTC
The create_release_and_deploy job periodically fails even though the version number has not changed.
This step should not create build failuers if the version number has not changed.

**Comment by ashutshkumr** [comment] 2020-12-14 09:27
Duplicate of https://github.com/open-traffic-generator/ixnetwork/issues/76

**Closed by ashutshkumr** 2020-12-14 09:27 UTC
Labels: duplicate
